# Generated by Django 3.2.3 on 2021-05-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
