# Generated by Django 3.2.3 on 2021-05-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_salaries_emp_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaries',
            options={'get_latest_by': 'to_date'},
        ),
    ]
