# Generated by Django 3.2.3 on 2021-05-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_salaries_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='emp_no',
            field=models.OneToOneField(db_column='emp_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='salaries', serialize=False, to='core.employee'),
        ),
    ]
